[snowflake]
SNOWFLAKE_ACCOUNT = "FRICGQR-GRB16275"
SNOWFLAKE_USER = "005VI00000FFVIIYA1"
SNOWFLAKE_PASSWORD = "8vxAVZS*y.&@4u"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "DEMO_DB"
SNOWFLAKE_SCHEMA = "PUBLIC"
