<<<<<<< HEAD
[myconnection]
account = "FRICGQR-GRB16275"
user = "005VI00000FFVIIYA1"
password = "8vxAVZS*y.&@4u"
warehouse = "COMPUTE_WH"
database = "DEMO_DB"
schema = "PUBLIC"
=======
[snowflake]
SNOWFLAKE_ACCOUNT = "FRICGQR-GRB16275"
SNOWFLAKE_USER = "005VI00000FFVIIYA1"
SNOWFLAKE_PASSWORD = "8vxAVZS*y.&@4u"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "DEMO_DB"
SNOWFLAKE_SCHEMA = "PUBLIC"
>>>>>>> ef0430c29acf759ee1e9dbf093b9b16a42a4ea89
